SNS-Login-Web/Areas/WorkFlow/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json.Linq;
using Project_WorkFlow.Application;
using Project_WorkFlow.Areas.WorkFlow.Models;
using Project_WorkFlow.Areas.WorkFlow.Services.Interfaces;
using Project_WorkFlow.Areas.WorkFlow.Services;

namespace Project_WorkFlow.Areas.WorkFlow.Controllers
{
    public class LoginController : Controller
    {

        // GET: WorkFlow/Login
        public ActionResult Index()
        {
            


            return View();
        }

        
        public ActionResult SignUp(UserModel model)
        {
            


            return View(model);
        }


        public ActionResult KakaoLogin()
        {
            string kakaoLoginUrl = KakaoAuthConfig.getKakaoLoginAuthUrl;


            return Redirect(kakaoLoginUrl);
        }

        public ActionResult KakaoSignUp()
        {
            string kakaoSignUpUrl = KakaoAuthConfig.getKakaoSignUpAuthUrl;


            return Redirect(kakaoSignUpUrl);
        }

        public ActionResult GetSignUpPermission()
        {


            return View();
        }

        public ActionResult TwitterLogin()
        {
            string authorizeUrl = TwitterAuthConfig.getTwitterAuthUrl;
            authorizeUrl += "&client_id=" + TwitterAuthConfig.getTwitterClientIdKey;
            authorizeUrl += "&redirect_uri=" + TwitterAuthConfig.getTwitterLoginRedirectUrl;
            authorizeUrl += TwitterAuthConfig.getTwitterScopeUrl;

            return Redirect(authorizeUrl);
        }

        public ActionResult TwitterSignUp()
        {
            string authorizeUrl = TwitterAuthConfig.getTwitterAuthUrl;
            authorizeUrl+="&client_id="+ TwitterAuthConfig.getTwitterClientIdKey;
            authorizeUrl+="&redirect_uri=" + TwitterAuthConfig.getTwitterSignUpRedirectUrl;
            authorizeUrl+= TwitterAuthConfig.getTwitterScopeUrl;

            return Redirect(authorizeUrl);
        }



    }
}

SNS-Login-Web/Areas/WorkFlow/Controllers/OAuthController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Text;
using System.IO;
using Newtonsoft.Json.Linq;
using Project_WorkFlow.Application;
using Project_WorkFlow.Areas.WorkFlow.Models;
using Project_WorkFlow.Areas.WorkFlow.Services.Interfaces;
using Project_WorkFlow.Areas.WorkFlow.Services;


namespace Project_WorkFlow.Areas.WorkFlow.Controllers
{
    public class OAuthController : Controller
    {
        private readonly IUserService userService;
        private readonly IAuthService authService;


        public OAuthController()
        {
            userService = new UserService();
            authService = new AuthService();

        }

        // GET: WorkFlow/OAuth/KakaoLoginProcess

        public ActionResult KakaoLoginProcess(string code)
        {
            string redirectController = string.Empty;
            string redirectAction = string.Empty;
            string redirectLoginUrl = KakaoAuthConfig.getKakaoLoginRedirectUrl;

            // json 파싱
            JObject token = authService.GetKakaoToken(redirectLoginUrl, code);

            // token에서 kakaoUserInfo 가져오기

            JObject userInfo = authService.GetKakaoUserInfo(token);
            long kakaoId = (long)userInfo["id"];
            string kakaoNickName = userInfo["kakao_account"]["profile"]["nickname"].ToString();

            //기존 회원인지 확인하기
            UserModel model = userService.GetUserId(kakaoId, kakaoNickName, "kakao");
            if (model._idx!=0)
            {
                Session["idx"] = model._idx;
                Session["email"] = model._emailData;
                Session["nickName"] = model._nickNameData;
                Session["profile"] = model._profileData;
                Session["snsName"] = model._snsNameData;

                redirectController = "Home";
                redirectAction = "Index";

            }
            else
            {
                //model = userService.InsertUser(kakaoId, kakaoEmail);
                //if (model._idx != 0)
                //{
                //    redirectController = "Home";
                //    redirectAction = "Index";
                //}

                TempData["snsId"] = kakaoId;
                redirectController = "Login";
                redirectAction = "SignUp";
            }

            return RedirectToAction(redirectAction,redirectController);

        }

        public ActionResult KakaoSignUpProcess(string code)
        {
            string redirectController = string.Empty;
            string redirectAction = string.Empty;
            string redirectSignUpUrl = KakaoAuthConfig.getKakaoSignUpRedirectUrl;

            // Token 가져오기
            JObject token = authService.GetKakaoToken(redirectSignUpUrl, code);

            // token에서 kakaoUserInfo 가져오기

            JObject userInfo = authService.GetKakaoUserInfo(token);
            long kakaoId = (long)userInfo["id"];
            string kakaoNickName = userInfo["kakao_account"]["profile"]["nickname"].ToString();

            //기존 회원인지 확인하기
            UserModel model = userService.GetUserId(kakaoId,kakaoNickName,"kakao");
            if (model._idx != 0)
            {
                TempData["idx"] = model._idx;
                redirectController = "Login";
                redirectAction = "SignUp";
            }
            else//기존회원이 아닐경우
            {

                TempData["token"] = token;
                TempData["snsName"] = "kakao";
                redirectController = "Login";
                redirectAction = "GetSignUpPermission";

            }


            return RedirectToAction(redirectAction, redirectController);

        }

        public JsonResult InsertUserProcess()
        {
            string redirectController = string.Empty;
            string redirectAction = string.Empty;

            string snsName = TempData["snsName"].ToString();
            JObject token = (JObject)TempData["token"];

            long snsId = new long();
            string snsNickName = string.Empty;

            // token에서 UserInfo 가져오기
            if (snsName == "kakao")
            {
                JObject userInfo = authService.GetKakaoUserInfo(token);
                snsId = (long)userInfo["id"];
                snsNickName = userInfo["kakao_account"]["profile"]["nickname"].ToString();
            }
            else if (snsName == "twitter")
            {
                JObject userInfo = authService.GetTwitterUserInfo(token);
                snsId = (long)userInfo["data"]["id"];
                snsNickName = userInfo["data"]["username"].ToString();

            }
            

            //기존 회원이 아닐경우
            UserModel model = userService.GetUserId(snsId, snsNickName, snsName);
            if (model._idx == 0)
            {
                model = userService.InsertUser(snsId, snsNickName, snsName);

            }


            return Json(model, JsonRequestBehavior.AllowGet);

        }

        public ActionResult TwitterLoginProcess(string code)
        {



            string redirectController = string.Empty;
            string redirectAction = string.Empty;
            string redirectUrl = TwitterAuthConfig.getTwitterLoginRedirectUrl;

            // Token 가져오기
            JObject token = authService.GetTwitterToken(redirectUrl, code);

            // token에서 twitterUserInfo 가져오기
            JObject userInfo = authService.GetTwitterUserInfo(token);
            long twitterId = (long)userInfo["data"]["id"];
            string twitterNickName = userInfo["data"]["username"].ToString();

            //기존 회원인지 확인하기
            UserModel model = userService.GetUserId(twitterId, twitterNickName, "twitter");
            if (model._idx != 0)
            {
                Session["idx"] = model._idx;
                Session["email"] = model._emailData;
                Session["nickName"] = model._nickNameData;
                Session["profile"] = model._profileData;
                Session["snsName"] = model._snsNameData;

                redirectController = "Home";
                redirectAction = "Index";

            }
            else
            {

                TempData["snsId"] = twitterId;
                redirectController = "Login";
                redirectAction = "SignUp";
            }


            return RedirectToAction(redirectAction, redirectController);


        }

        public ActionResult twitterSignUpProcess(string code)
        {

            

            string redirectController = string.Empty;
            string redirectAction = string.Empty;
            string redirectUrl = TwitterAuthConfig.getTwitterSignUpRedirectUrl;

            // Token 가져오기
            JObject token = authService.GetTwitterToken(redirectUrl, code);

            // token에서 twitterUserInfo 가져오기
            JObject userInfo = authService.GetTwitterUserInfo(token);
            long twitterId = (long)userInfo["data"]["id"];
            string twitterNickName = userInfo["data"]["username"].ToString();

            //기존 회원인지 확인하기
            UserModel model = userService.GetUserId(twitterId, twitterNickName, "twitter");
            if (model._idx != 0)
            {
                TempData["idx"] = model._idx;
                redirectController = "Login";
                redirectAction = "SignUp";
            }
            else//기존회원이 아닐경우
            {

                TempData["token"] = token;
                TempData["snsName"] = "twitter";
                redirectController = "Login";
                redirectAction = "GetSignUpPermission";

            }


            return RedirectToAction(redirectAction, redirectController);


        }






    }
}

SNS-Login-Web/Areas/WorkFlow/Views/Login/GetSignUpPermission.cshtml
@{
    Layout = "~/Areas/WorkFlow/Views/Shared/_LoginLayout.cshtml";
}

<div class="main-wrap">
    <header>
        <div class="logo-wrap">
            <h2>작업 일정 공유 사이트</h2>
        </div>


    </header>

    <section class="Easy-sgin-in-wrap">
        <h2>간편 회원가입</h2>
        <ul class="sign-button-list">
            <li><button type="button" onclick="fnSignup('/InsertUserProcess')" style="cursor: pointer; width: 300px; height: 45px;">사이트 이용에 동의하면 클릭해주세요.</button></li>

            @*@using (Ajax.BeginForm("KakaoInsertUserProcess", "OAuth", null,new AjaxOptions { HttpMethod = "POST", OnSuccess = "OnSuccess" })
            {
                @Html.
            }*@


        </ul>
    </section>


</div>

SNS-Login-Web/Areas/WorkFlow/Views/Login/Index.cshtml
@{
    Layout = "~/Areas/WorkFlow/Views/Shared/_LoginLayout.cshtml";
}

<div class="main-wrap">
    <header>
        <div class="logo-wrap">
            <h2>작업 일정 공유 사이트</h2>
        </div>


    </header>

    <section class="Easy-sgin-in-wrap">
        <h2>간편 로그인</h2>
        <ul class="sign-button-list">
            <li><button type="button" onclick="window.location.href='./KakaoLogin'" style="cursor:pointer;"><img src="~/Common/img/kakao_Large and Narrow (300px X 45px).png" style="width:300px; height:45px; text-align:center;" /></button></li>
            <li><button type="button" onclick="window.location.href='./twitterLogin'" style="cursor:pointer;"><img src="~/Common/img/Twitter(300px X 45px).png" style="width: 300px; height: 45px; " /></button></li>
        </ul>
        <a href="./SignUp"><p class="forget-msg">회원가입</p></a>
    </section>


</div>

SNS-Login-Web/Areas/WorkFlow/Views/Login/SignUp.cshtml
@{

    if (TempData.ContainsKey("snsId") && (long)TempData["snsId"] != 0)
    {
       <script>
            alert("사이트 회원가입이 필요합니다.");
       </script>
    }
    else if(TempData.ContainsKey("idx") && (long)TempData["idx"] != 0)
    {
        <script>
            alert("기존 회원입니다. 로그인을 진행해주세요.");
            window.location.href="https://www.workflow.com/workflow/login/index"
        </script>
    }

    


}


@{
    Layout = "~/Areas/WorkFlow/Views/Shared/_LoginLayout.cshtml";
}



<div class="main-wrap">
    <header>
        <div class="logo-wrap">
            <h2>작업 일정 공유 사이트</h2>
        </div>
    </header>
    
    <section class="Easy-sgin-in-wrap">
        <h2>간편 회원가입</h2>
        <ul class="sign-button-list">
            <li><a href="./KakaoSignUp"><img src="~/Common/img/kakao_signup(300px X 45px).png" style="width:300px; height:45px; text-align:center;" /></a></li>
            <li><a href="./twitterSignUp"><img src="~/Common/img/twitter_signup(300px X 45px).png" style="width:300px; height:45px;" /></a></li>
        </ul>

    </section>


</div>